version: '3'

services:
  java:
    image: java
    volumes:
      - '~\.m2\repository:/root/.m2/repository'
      - '~\git\webflow-2020-06:/var/app'
    command: ['java', '-Xms1g', '-jar', '/var/app/target/webflow-2020-06-0.0.1-SNAPSHOT.jar']
    ports:
      - '8080:8080'
      - '8000:8000'
